### ISSUE TITLE
I'm trying to access our sonarqube instance running in AWS from k8s, using the configuration:

### ISSUE THREAD

**Issue by Jaff** [dmeiners88/sonarqube-prometheus-exporter#17]
I'm trying to access our sonarqube instance running in AWS from k8s, using the configuration:
```
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: sonar-prometheus
  namespaceSelector:
    matchNames:
        - monitoring
  endpoints:
  - targetPort: 443
    scheme: https
    interval: 30s
    path: /api/prometheus/metrics
    bearerTokenSecret:
      key: auth-token
```
I know that I can get the metrics returned by using `curl -u<SECRET>: https://serverhost/api/prometheus/metrics` but I am not seeing these within our Grafana service.

_Originally posted by @Jaff in https://github.com/dmeiners88/sonarqube-prometheus-exporter/issues/14#issuecomment-1009212374_
